import {useState,useRef} from 'react';
import {previewRoster,type RosterPreview} from '../../domain/roster';
import {type SchoolContext,type Student} from '../../domain/model';
import {firebase} from '../../data/firebase';
import {importStudents,planImport,type PlannedStudent} from '../../data/schoolRepository';
const sample='학년\t이름\n1학년\t가상 시민 하나\n2학년\t가상 시민 둘\n5학년\t가상 시민 셋';
export function RosterImport({demo=false,context,existing=[],onDone}:{demo?:boolean;context?:SchoolContext;existing?:Student[];onDone?:()=>void}){
  const [text,setText]=useState(demo?sample:''),[className,setClassName]=useState(''),[year,setYear]=useState(new Date().getFullYear()),[preview,setPreview]=useState<RosterPreview|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false);
  const plan=useRef<{id:string;rows:PlannedStudent[]}|null>(null);
  function clearPreview(){setPreview(null);setConfirmed(false);plan.current=null;setError('')}
  function inspect(){try{const p=previewRoster(text,className||null);if(p.rows.length>50)p.issues.push({row:0,message:'등록은 한 번에 최대 50명입니다. 나누어 확인해 주세요.'});if(existing.length>=100)p.issues.push({row:0,message:'전체 명단 중복 확인을 위해 100명 이상 학교는 이 단계에서 가져오기를 차단합니다.'});for(const r of p.rows)if(existing.some(s=>s.grade===r.grade&&s.name===r.name&&s.className===r.className))p.issues.push({row:r.sourceRow,message:'기존 명단에 같은 학년·반·이름이 있습니다. 기존 시민 ID를 확인해 주세요.'});setPreview(p);setError('');plan.current={id:crypto.randomUUID(),rows:planImport(p.rows)}}catch(e){setError((e as Error).message);setPreview(null)}}
  async function save(){if(demo||!context||!firebase||!preview||preview.issues.length||!confirmed||!plan.current||busy)return;setBusy(true);setError('');try{await importStudents(firebase.db,context,plan.current.id,plan.current.rows,year);setText('');setPreview(null);plan.current=null;onDone?.()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <div><div className="section-heading"><h2>학생 명단 확인</h2>{demo&&<span className="tag">가상 자료 · 저장 안 함</span>}</div><p>시트에서 <b>학년·이름</b> 열을 제목부터 복사해 넣어 주세요. 반은 미지정으로 남기거나 직접 지정할 수 있습니다.</p>
    {demo?<div className="notice">실제 명단 입력은 학교 연결 후 교사 화면에서만 가능합니다.</div>:<label>CSV 또는 TSV 파일<input type="file" accept=".csv,.tsv,text/csv,text/tab-separated-values" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;clearPreview();if(file.size>100_000){setError('100KB 이하 파일을 선택해 주세요.');return}setText(await file.text())}}/></label>}
    <label>명단 내용<textarea value={text} readOnly={demo} disabled={busy} rows={6} onChange={e=>{setText(e.target.value);clearPreview()}} placeholder={'학년\t이름\n1학년\t학생 이름'}/></label><div className="fields"><label>공통 반 (선택)<input value={className} disabled={busy} maxLength={20} onChange={e=>{setClassName(e.target.value);clearPreview()}} placeholder="미지정"/></label><label>학년도<input type="number" value={year} min={2020} max={2100} disabled={busy} onChange={e=>{setYear(Number(e.target.value));clearPreview()}}/></label></div><button className="button secondary" disabled={busy} onClick={inspect}>등록 전 확인</button>{error&&<p className="error" role="alert">{error}</p>}
    {preview&&<div className="section"><div className="section-heading"><h3>확인한 학생 {preview.rows.length}명</h3><span className="tag">오류 {preview.issues.length}건</span></div>{preview.issues.length>0&&<ul role="alert" className="error">{preview.issues.map((i,n)=><li key={n}>{i.row?`${i.row}행: `:''}{i.message}</li>)}</ul>}<div className="table-scroll"><table><thead><tr><th>원본 행</th><th>학년</th><th>반</th><th>이름</th></tr></thead><tbody>{preview.rows.map(r=><tr key={r.sourceRow}><td>{r.sourceRow}</td><td>{r.grade}학년</td><td>{r.className??'미지정'}</td><td>{r.name}</td></tr>)}</tbody></table></div>{!demo&&<><label className="checkbox"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/>대상 학교·학년도와 명단을 확인했습니다. 로그인 계정 발급은 별도입니다.</label><button className="button primary" disabled={busy||!confirmed||preview.issues.length>0} onClick={save}>{busy?'등록 중…':`${preview.rows.length}명 시민 등록`}</button></>} {demo&&<p className="notice">형식 확인이 끝났습니다. 이 화면은 데이터를 저장하지 않습니다.</p>}</div>}
  </div>;
}
