import {useEffect,useRef,useState,type FormEvent} from 'react';
import {canAssign,departments,jobIcons,iconNames,statuses,type Application,type Career,type CareerData} from '../../domain/jobs';
import {toMajor,toMinor} from '../../domain/money';
import type {Student} from '../../domain/model';
import type {CareerStore} from '../../data/careerRepository';

export function CareerWorkspace({store,schoolId,teacher,students,studentId,onChange}:{store:CareerStore;schoolId:string;teacher:boolean;students:Student[];studentId?:string;onChange?:()=>void}){
  const [data,setData]=useState<CareerData>({jobs:[],applications:[],assignments:[]}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  const [filter,setFilter]=useState('all'),[view,setView]=useState<'jobs'|'applications'|'assignments'>('jobs'),[editing,setEditing]=useState<Career|null>(null),[applying,setApplying]=useState<Career|null>(null),[reviewing,setReviewing]=useState<Application|null>(null);
  const mounted=useRef(true);
  useEffect(()=>{mounted.current=true;let alive=true;setLoading(true);store.load().then(d=>{if(alive)setData(d)}).catch(e=>{if(alive)setError(e.message)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false;mounted.current=false}},[store]);
  async function run(action:()=>Promise<void>,success:string){if(busy)return;setBusy(true);setError('');setMessage('');try{await action();const next=await store.load();if(mounted.current){setData(next);setMessage(success);setApplying(null);setEditing(null);setReviewing(null);onChange?.()}}catch(e){if(mounted.current)setError((e as {code?:string}).code==='permission-denied'?'학교 접근 권한을 확인할 수 없습니다. 다시 로그인해 주세요.':(e as Error).message)}finally{if(mounted.current)setBusy(false)}}
  const mine=data.assignments.filter(a=>a.status==='active'&&(teacher||a.studentId===studentId));
  const jobs=data.jobs.filter(j=>filter==='all'||j.departmentId===filter);
  const studentName=(id:string)=>students.find(s=>s.id===id)?.name??'현재 명단 밖의 시민';
  const jobName=(id:string)=>data.jobs.find(j=>j.id===id)?.name??id;
  return <section className="careers"><div className="page-heading"><div><span className="eyebrow">나의 역할, 우리의 사회</span><h1>{teacher?'직업 운영실':'나에게 맞는 직업 찾기'}</h1><p>{teacher?'직업을 준비하고, 시민의 신청을 살펴보고, 역할을 배정해요.':'하고 싶은 일을 찾아 신청해 보세요. 여러 직업을 함께 맡을 수 있어요.'}</p></div>{teacher&&<button className="button primary" onClick={()=>setEditing({id:crypto.randomUUID(),schoolId,departmentId:'life',name:'',description:'',core:false,status:'preparing',recommendedGrades:[1,2,3,4,5,6],icon:'plant_manager',salaryMinor:0,schemaVersion:1})}>+ 직업 만들기</button>}</div>
    <nav className="workspace-tabs" aria-label="직업 메뉴">{([['jobs','직업 둘러보기'],['applications',teacher?'신청 검토':'내 신청 내역'],['assignments',teacher?'직업 배정':'내 직업']] as const).map(([id,label])=><button key={id} aria-pressed={view===id} onClick={()=>{setView(id);setApplying(null);setEditing(null);setReviewing(null)}}>{label}{id==='applications'&&<span>{data.applications.filter(a=>a.status==='submitted').length}</span>}</button>)}</nav>
    {error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status" className="success">{message}</p>}
    {loading?<p role="status">직업을 불러오고 있어요.</p>:<>
      {editing&&<CareerEditor key={editing.id} job={editing} busy={busy} onCancel={()=>setEditing(null)} onSave={job=>run(()=>store.save(job),'직업을 저장했습니다.')}/>}
      {applying&&<form className="panel section action-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>store.apply(applying.id,String(f.get('reason'))),'신청했습니다. 선생님의 배정을 기다려 주세요.')}}><h2>{applying.name} 신청하기</h2><label>이 일을 하고 싶은 이유<textarea autoFocus name="reason" required maxLength={500} rows={3}/></label><div className="header-actions"><button className="button primary" disabled={busy}>신청 보내기</button><button type="button" className="button quiet" onClick={()=>setApplying(null)}>취소</button></div></form>}
      {view==='jobs'&&<><div className="department-filters"><button aria-pressed={filter==='all'} onClick={()=>setFilter('all')}>전체 직업 <strong>{data.jobs.length}</strong></button>{departments.map(d=><button key={d.id} aria-pressed={filter===d.id} onClick={()=>setFilter(d.id)}><img src={`/assets/departments/${d.icon}_department_icon.png`} alt=""/>{d.name}</button>)}</div>
        {!data.jobs.length?<div className="panel empty"><h2>아직 등록된 직업이 없어요</h2><p>{teacher?'기본 직업 6개로 시작하거나 우리 학교만의 직업을 만들어 보세요.':'선생님이 직업을 준비하고 있어요.'}</p>{teacher&&<button className="button primary section" disabled={busy} onClick={()=>run(()=>store.seed(),'기본 직업을 준비했습니다.')}>기본 직업으로 시작</button>}</div>:!jobs.length?<p className="empty">이 국에는 아직 직업이 없어요.</p>:<div className="job-grid">{jobs.map(job=>{const a=data.applications.find(a=>a.jobId===job.id&&a.studentId===studentId),assigned=mine.some(a=>a.jobId===job.id);return <article className={`job-card department-${job.departmentId}`} key={job.id}><div className="job-top"><img className="job-icon" src={`/assets/jobs/${job.icon}_job_icon.png`} alt=""/><span className={`job-status status-${job.status}`}>{statuses[job.status]}</span></div><span className="job-department">{departments.find(d=>d.id===job.departmentId)?.name}{job.core?' · 핵심 직업':''}</span><h2>{job.name}</h2><p>{job.description}</p><div className="job-grades">권장 {job.recommendedGrades.join('·')}학년 <small>다른 학년도 신청 가능</small></div>{teacher?<button className="button quiet full" disabled={job.status==='closed'} onClick={()=>setEditing(job)}>{job.status==='closed'?'종료 기록 보존 중':'직업 설정'}</button>:<button className="button primary full" disabled={job.status!=='recruiting'||!!a||assigned||busy} onClick={()=>setApplying(job)}>{assigned?'내가 맡은 직업':a?'신청 내역 확인':job.status==='recruiting'?'이 직업 신청하기':statuses[job.status]}</button>}</article>})}</div>}
      </>}
      {view==='applications'&&<section className="panel section"><h2>{teacher?'시민들의 신청':'내 신청 내역'}</h2>{data.applications.length?data.applications.map(a=><article className="application-row" key={a.id}><div><span className={`job-status status-${a.status==='submitted'?'preparing':a.status==='approved'?'active':'closed'}`}>{a.status==='submitted'?'검토 대기':a.status==='approved'?'배정 완료':'반려'}</span><h3>{jobName(a.jobId)}{teacher?` · ${studentName(a.studentId)}`:''}</h3><p>{a.reason}</p>{a.reviewNote&&<p className="review-note">선생님 의견: {a.reviewNote}</p>}</div>{teacher&&a.status==='submitted'&&<button className="button secondary" onClick={()=>setReviewing(a)}>신청 검토</button>}</article>):<p className="empty">아직 신청 내역이 없어요.</p>}
        {reviewing&&<form className="action-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),approve=(e.nativeEvent as SubmitEvent).submitter?.getAttribute('value')==='approve';void run(()=>store.review(reviewing,approve,String(f.get('note'))),approve?'신청을 승인하고 직업을 배정했습니다.':'반려 의견을 남겼습니다.')}}><h3>{jobName(reviewing.jobId)} · {studentName(reviewing.studentId)}</h3><label>검토 의견 (반려할 때 필수)<textarea autoFocus name="note" maxLength={500} rows={2}/></label><div className="header-actions"><button className="button primary" value="approve" disabled={busy}>승인하고 배정</button><button className="button quiet" value="reject" disabled={busy}>반려</button><button className="button quiet" type="button" onClick={()=>setReviewing(null)}>닫기</button></div></form>}
      </section>}
      {view==='assignments'&&<section className="panel section"><h2>{teacher?'시민별 직업 배정':'내가 맡은 직업'}</h2>{teacher&&<form className="assignment-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>store.assign(String(f.get('job')),String(f.get('student'))),'직업을 배정했습니다.')}}><label>학생<select name="student" required><option value="">학생 선택</option>{students.filter(s=>s.status==='active').map(s=><option value={s.id} key={s.id}>{s.name} · {s.grade}학년</option>)}</select></label><label>직업<select name="job" required><option value="">직업 선택</option>{data.jobs.filter(canAssign).map(j=><option key={j.id} value={j.id}>{j.name}</option>)}</select></label><button className="button primary" disabled={busy}>직업 배정</button></form>}{mine.length?mine.map(a=><div className="application-row" key={a.id}><div><h3>{jobName(a.jobId)}</h3><p>{teacher?studentName(a.studentId):'나의 역할'} · {statuses[data.jobs.find(j=>j.id===a.jobId)?.status??'closed']}</p></div>{teacher&&<button className="button quiet" disabled={busy} onClick={()=>run(()=>store.end(a),'배정을 종료했습니다.')}>배정 종료</button>}</div>):<p className="empty">아직 맡은 직업이 없어요. 직업을 신청하고 선생님의 배정을 기다려 주세요.</p>}</section>}
      {(data.jobs.length===100||data.applications.length===100||data.assignments.length===100)&&<p className="notice">목록은 최대 100건까지 표시합니다. 이보다 많은 기록의 조회는 다음 운영 단계에서 지원합니다.</p>}
    </>}
  </section>;
}
function CareerEditor({job,busy,onSave,onCancel}:{job:Career;busy:boolean;onSave:(j:Career)=>void;onCancel:()=>void}){
  const [grades,setGrades]=useState(job.recommendedGrades);
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);onSave({...job,name:String(f.get('name')).trim(),description:String(f.get('description')).trim(),departmentId:String(f.get('department')),status:String(f.get('status')) as Career['status'],core:job.core||f.get('core')==='on',icon:String(f.get('icon')),recommendedGrades:grades,salaryMinor:toMinor(Number(f.get('salary'))||0)})}
  return <form className="panel section action-form" onSubmit={submit}><h2>{job.name?'직업 설정':'새 직업 만들기'}</h2><div className="fields"><label>직업 이름<input autoFocus name="name" defaultValue={job.name} required maxLength={60}/></label><label>소속국<select name="department" defaultValue={job.departmentId}>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></div><label>하는 일<textarea name="description" defaultValue={job.description} required maxLength={1000} rows={3}/></label><div className="fields"><label>운영 상태<select name="status" defaultValue={job.status}>{Object.entries(statuses).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>직업 아이콘<select name="icon" defaultValue={job.icon}>{jobIcons.map(icon=><option value={icon} key={icon}>{iconNames[icon]}</option>)}</select></label></div><label>월급(마동, 매달 정산)<input name="salary" type="number" min={0} max={10000} step={1} defaultValue={toMajor(job.salaryMinor)}/></label><fieldset><legend>권장 학년 (신청을 제한하지 않아요)</legend><div className="grade-options">{[1,2,3,4,5,6].map(g=><label className="checkbox" key={g}><input type="checkbox" checked={grades.includes(g)} onChange={e=>setGrades(e.target.checked?[...grades,g].sort():grades.filter(n=>n!==g))}/>{g}학년</label>)}</div></fieldset><label className="checkbox"><input type="checkbox" name="core" defaultChecked={job.core} disabled={job.core}/>작은 사회를 유지하는 핵심 직업</label><p className="muted">운영 종료 후에도 기록은 보존되며 신규 신청과 배정은 닫힙니다.</p><div className="header-actions section"><button className="button primary" disabled={busy}>직업 저장</button><button className="button quiet" type="button" onClick={onCancel}>취소</button></div></form>;
}
